version: "1"

services:
    dvwa:
        build: ./image_php
        ports:
            - "8082:80"
        volumes:
            - ./source:/var/www/html/
        links:
            - db2
        depends_on:
            - db2
    db2:
        image: mysql
        container_name: db2
        ports:
            - "3307:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment: 
            MARIADB_ROOT_PASSWORD: p@ssw0rd
            MYSQL_DATABASE: lms
            MYSQL_USER: lms
            MYSQL_ROOT_PASSWORD: p@ssw0rd
            MYSQL_PASSWORD: p@ssw0rd
        volumes:
            - lms_db:/var/lib/mysql
            - ./init:/docker-entrypoint-initdb.d
    phpmyadmin-lms:
        container_name: phpmyadmin-lms
        image: phpmyadmin/phpmyadmin
        ports:
            - "8083:80"
        environment:
            MYSQL_USER: lms
            MYSQL_ROOT_PASSWORD: p@ssw0rd
            MYSQL_PASSWORD: p@ssw0rd
            # database host port
            PMA_HOST: db2
            PMA_USER: root
            PMA_PASSWORD: p@ssw0rd
volumes:
    lms_db:
networks:
    default:
